#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
# 你可以从指南中获得更详细的说明
#
# Guide: https://hexo.fluid-dev.com/docs/en/guide/
# You can get more detailed help from the guide
#---------------------------


#---------------------------
# 全局
# Global
#---------------------------

# 用于浏览器标签的图标
# Icon for browser tab
favicon: /img/favicon.png

# 用于苹果设备的图标
# Icon for Apple touch
apple_touch_icon: /img/favicon.png

#
#
missing_image: /img/missing.png

# 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
# Title separator in browser tab, eg: article - site
tab_title_separator: " - "

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
# Force all links to be HTTPS (applicable to HTTP mixed error)
force_https: false

# 默认的选项，选择 `auto` 会优先遵循 prefers-color-scheme
# Default option, choosing `auto` will give priority to prefers-color-scheme
# Options: auto | light | dark
color_scheme: auto


# pjax 支持
#
pjax:
  enable: true
  #
  #
  options:
    #
    #
    selectors:
      - "head title"
      - "script[data-config]"
      - ".pjax"
    #
    #
    analytics: false
    #
    #
    cacheBust: false


loading_box:
  enable: true
  image_src: /img/genshin_loading.png
  close_tip: 点击任意处关闭


# 压缩文件大小
#
minify:
  # 压缩 HTML
  #
  html:
    enable: true
    options:
      removeAttributeQuotes: false
      collapseBooleanAttributes: true
      collapseWhitespace: true
      ignoreCustomComments:
        - ^\s*more # Ignore '<!-- more -->' https://hexo.io/docs/tag-plugins#Post-Excerpt
      removeComments: true
      removeEmptyAttributes: true
      removeScriptTypeAttributes: true
      removeStyleLinkTypeAttributes: true
      minifyJS: true
      minifyCSS: true

  # 压缩 JS
  #
  js:
    enable: true
    options:

  # 压缩 CSS
  #
  css:
    enable: true
    options:

  # 压缩本地字体
  #
  local_fonts:
    enable: true
    # 全局保留的字符
    #
    preserved_chars: 1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
    # 字体列表
    #
    includes:
        # 字体文件路径
        #
      # - path: _font/GenshinImpact.ttf
      #   # 字体文件导出路径
      #   #
      #   export_path: font/GenshinImpact.ttf
      #   # 需要保留的字符
      #   #
      #   preserved_chars:
      #     # HTML 中的字符
      #     #
      #     html: true
      #     # 额外保留的字符
      #     #
      #     custom: ★ω祝觑哇迎握手党棒浪厉害拿青佬坛旅途愉快昵称星穹铁道


iconfont:
  links:
    - //at.alicdn.com/t/c/font_3495329_rsmj9wo3izg.css # 主题内置图标库

  class_map:
    time: iconfont icon-time
    more: iconfont icon-more-fill
    fire: iconfont icon-fire-fill
    notice: iconfont icon-pen-fill
    pen: iconfont icon-pen-fill
    tags: iconfont icon-tags
    categories: iconfont icon-category
    comment: iconfont icon-comments
    mouse: iconfont icon-mouse
    search: iconfont icon-search
    user: iconfont icon-user
    sun: iconfont icon-sun
    moon: iconfont icon-moon
    home: iconfont icon-home
    view: iconfont icon-view
    share: iconfont icon-share
    cc: iconfont icon-cc
    by: iconfont icon-cc-by
    sa: iconfont icon-cc-sa
    nc: iconfont icon-cc-nc
    nd: iconfont icon-cc-nd
    arrowleft: iconfont icon-arrow-left
    arrowright: iconfont icon-arrow-right
    arrowdown: &arrow-down-icon iconfont icon-arrow-down
    arrowup: iconfont icon-arrow-up
    music: iconfont icon-music
    musicForbidden: iconfont icon-music-no
    close: iconfont icon-close
    loop: iconfont icon-loop
    loopOne: iconfont icon-loop-1
    random: iconfont icon-random-play
    musicPrev: iconfont icon-previous-music
    musicNext: iconfont icon-next-music
    playlist: iconfont icon-play-list
    play: iconfont icon-play
    pause: iconfont icon-pause
    playing: &music-playing-icon iconfont icon-music-playing


css_vars:
  light:
    --scrollbar-track-color: "#fdfdfd"
    --scrollbar-thumb-color: "#35b995cc"
    --scrollbar-thumb-hover-color: "#35B995"
    --main-bg-color: "#fdfdfd"

    --text-color: "#24292f"
    --text-sec-color: "#6f6f6f"

    --msg-box-bg-color: "#f2f2f2"
    --msg-box-text-color: "#505050"

    --icon-highlight-color: "#A0DAD0"

    --separator-line-color: "#ECECEC"

    --img-border-color: "#DADADA"


    --color-fg-default: "#24292f"
    --color-fg-muted: "#57606a"
    --color-fg-subtle: "#6e7781"
    --color-canvas-default: "#fdfdfd"
    --color-canvas-subtle: "#f2f2f2"
    --color-canvas-hover: "#eff2f3"
    --color-border-default: "#d0d7de"
    --color-border-muted: "hsla(210,18%,87%,1)"
    --color-neutral-muted: "rgba(175,184,193,0.2)"
    --color-accent-fg: "#0969da"
    --color-accent-emphasis: "#0969da"
    --color-attention-subtle: "#fff8c5"
    --color-danger-fg: "#cf222e"

  dark:
    --scrollbar-track-color: "#fff0"
    --scrollbar-thumb-color: "#35b995cc"
    --scrollbar-thumb-hover-color: "#35B995"
    --main-bg-color: "#171717"

    --main-text-color: "rgba(255, 255, 255, 0.7)" # remove
    --main-text2-color: "#afafaf" # remove
    --main-info-color: "#202020"  # remove

    --msg-box-bg-color: "#202020"
    --msg-box-text-color: "#E5E5E5"

    --text-color: "rgba(255, 255, 255, 0.7)" # #aaa
    --text-sec-color: "#afafaf"

    --link-color: "#E67474"
    --link-hover-color: "#72C5A6"

    --icon-highlight-color: "#A0DAD0"

    --separator-line-color: "#2c2c2c"

    --img-border-color: "#303030"

    --img-br: "#303030" # remove
    --br-color: "#2c2c2c" # remove

    --color-fg-default: "rgba(255, 255, 255, 0.7)"
    --color-fg-muted: "#8b949e"
    --color-fg-subtle: "#484f58"
    --color-canvas-default: "#171717"
    --color-canvas-subtle: "#202020"
    --color-canvas-hover: "#363636"
    --color-border-default: "#30363d"
    --color-border-muted: "#21262d"
    --color-neutral-muted: "rgba(110,118,129,0.4)"
    --color-accent-fg: "#58a6ff"
    --color-accent-emphasis: "#1f6feb"
    --color-attention-subtle: "rgba(187,128,9,0.15)"
    --color-danger-fg: "#f85149"





# 代码块的增强配置
# Enhancements to code blocks
code:
  # 是否开启复制代码的按钮
  # Enable copy code button
  copy_btn: true

  #
  #
  fold:
    enable: true
    #
    #
    maxHeight: 300
    #
    #
    downArrowIcon: *arrow-down-icon

  # 代码高亮
  # Code highlight
  highlight:
    enable: true

    # 代码块是否显示行号
    # If true, the code block display line numbers
    line_number: true

    # 实现高亮的库，对应下面的设置
    # Highlight library
    # Options: highlightjs | prismjs
    lib: "prismjs"

    highlightjs:
      # 在链接中挑选 style 填入
      # Select a style in the link
      # See: https://highlightjs.org/static/demo/
      style: "Vs 2015"

      # 是否根据 style 改变代码背景色（如果 style 是深色背景别忘了开启此项）
      # If true, the code background will change color based on the style (If style has a dark background, don't forget to true)
      bg_color: true

    prismjs:
      # 在下方链接页面右侧的圆形按钮挑选 style 填入，也可以直接填入 css 链接
      # Select the style button on the right side of the link page, you can also set the CSS link
      # See: https://prismjs.com/
      style: "https://cdn.jsdelivr.net/npm/prism-themes@1/themes/prism-vsc-dark-plus.min.css"

      # 设为 true 高亮将本地静态生成（并只支持部分 prismjs 插件），设为 false 高亮将在浏览器通过 js 生成
      # If true, it will be generated locally (but some prismjs plugins are not supported). If false, it will be generated via JS in the browser
      preprocess: true



# 主题字体配置
# Font
font:
  font_size: 16px
  font_family: Tauri,'JetBrains Mono','Noto Sans SC','Microsoft YaHei',sans-serif
  letter_spacing: 0.02em
  code_font_size: 85%





author:
  name: Stalo
  avatar: /images/avatar.jpg
  desc: 莫等闲、白了少年头，空悲切。


share:
  wechat:
    enable: true
    icon: /img/wechat.png
  qzone:
    enable: true
    icon: /img/qzone.png
  sina:
    enable: true
    icon: /img/sina.png


navbar:
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home" }
    - {
        key: "文章",
        icon: "iconfont icon-post",
        submenu: [
          { key: "archive", link: "/archives/", icon: 'iconfont icon-timeline' },
          { key: "category", link: "/categories/", icon: 'iconfont icon-category' },
          { key: "tag", link: "/tags/", icon: 'iconfont icon-tags' }
        ]
      }
    - { key: "links", link: "/links/", icon: 'iconfont icon-link' }
    - { key: "感谢", link: "/thanks/", icon: 'iconfont icon-love' }
    - { key: "开往", link: "https://travellings.link", icon: 'iconfont icon-subway' }
    - { key: "about", link: "/about/", icon: 'iconfont icon-user' }


# 首屏图片的相关配置
# Config of the big image on the first screen
banner:
  # 图片最小的宽高比，以免图片两边被过度裁剪，适用于移动端竖屏时，如需关闭设为 0
  # Minimum ratio of width to height, applicable to the vertical screen of mobile device, if you need to close it, set it to 0
  width_height_ratio: 0 #1.0

  # 动态切换图片
  #
  dynamic_loop:
    enable: true

    # 每张图的时间
    #
    each_seconds: 6

    # 图片数量（此值应该大于 2）
    #
    img_count: 6

    # 图片库（当数量不足时从这里补充）
    #
    img_library:
      - https://tva1.sinaimg.cn/large/6833939bly1gipet4bz0yj20zk0m8e81.jpg
      - https://tva4.sinaimg.cn/large/6833939bly1giclwuom7cj20zk0m8dvn.jpg
      - https://tva4.sinaimg.cn/large/6833939bly1gipexj2jgzj20zk0m8b09.jpg
      - https://tva4.sinaimg.cn/large/6833939bly1gicit31ffoj20zk0m8naf.jpg
      - https://tva4.sinaimg.cn/large/6833939bly1gicitzannuj20zk0m8b29.jpg

  # 默认样式
  #
  default_styles:
    video:
      fit: cover
      pos: 50% 50%
    pic:
      size: cover
      pos: 50% 50%


# 向下滚动的提示
# Scroll down tip
scroll_down_tip:
  enable: true

  # 头图高度不小于指定比例，才显示提示
  # Only the height of the banner image is greater than the ratio, the tip is displayed
  # Available: 0 - 100
  banner_height_limit: 80

  # 翻页后自动滚动
  # Auto scroll after page turning
  scroll_after_turning_page: true

# 搜索功能，基于 hexo-generator-search 插件，若已安装其他搜索插件请关闭此功能，以避免生成多余的索引文件
# Search feature, based on hexo-generator-search. If you have installed other search plugins, please disable this feature to avoid generating redundant index files
search:
  enable: true

  # 搜索索引文件的路径，可以是相对路径或外站的绝对路径
  # Path for search index file, it can be a relative path or an absolute path
  path: /local-search.xml

  # 文件生成在本地的位置，必须是相对路径
  # The location where the index file is generated locally, it must be a relative location
  generate_path: /local-search.xml

  # 搜索的范围
  # Search field
  # Options: post | page | all
  field: post

  # 搜索是否扫描正文
  # If true, search will scan the post content
  content: true


index:
  slogan:
    enable: true
    text: 开发中画面，不代表最终品质 #TECH OTAKUS SAVE THE WORLD

  special_banner:
    enable: true

  # 可行的参数
  # 1. 给一个 url                            -> single   pic banner
  # 2. 给一个 url[]                          -> multiple pic banner
  # 4. 给一个 { pic, size?, pos? }           -> single   pic banner
  # 3. 给一个 { pic, size?, pos? }[]         -> multiple pic banner
  # 5. 给一个 { video, poster?, fit?, pos? } -> video        banner
  banner_img:
    video: https://gcore.jsdelivr.net/gh/Jin-Yuhan/WebAssetStorage@latest/videos/hutao.mp4
    poster: /images/poster.jpg
    fit: cover
    pos: 70% 50%

  banner_img_height: 100

  banner_mask_alpha: 0.4

  notice: 先别急，主题还在开发中。

  auto_excerpt:
    enable: true

post:
  # 版权声明，会显示在每篇文章的结尾（可在文章中单独配置）
  # Copyright, will be displayed at the end of each post
  # 在 content 中填写下述选项可激活 CC 协议，输入其他文本则直接显示
  # Fill in the following options in the content to activate the CC agreement, or enter other text to display directly
  # CC 协议选项 Options: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND
  copyright:
    enable: true
    content: BY-NC-SA

  # 文章底部上一篇下一篇功能
  # Link to previous/next post
  prev_next:
    enable: true



footer:
  content: >-
    Framework <a href="https://hexo.io" target="_blank" rel="nofollow noopener">Hexo</a> | Theme <a href="https://github.com/Jin-Yuhan/hexo-theme-anemo" target="_blank" rel="nofollow noopener">Anemo</a>
    <br>
    ©2020-2022 Stalo. All rights reserved.


archive:
  title: 文章归档

page:
  title:


tag:
  enable: true
  banner_img: 
  banner_img_height: 100
  banner_mask_alpha: 0.4
  title: 标签云
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"

category:
  enable: true
  banner_img:
  banner_img_height: 100
  banner_mask_alpha: 0.4
  subtitle:

  # 分类的排序字段，前面带减号是倒序，不带减号是正序
  # Sort field for categories, with a minus sign is reverse order
  # Options: length | name
  order_by: "-length"

  # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在子分类则默认展开
  # Collapse depth. If 0, all posts collapsed. If greater than 0, it will be expanded by default if there are subcategories
  collapse_depth: 0

  # 文章的排序字段，前面带减号是倒序，不带减号是正序
  # Sort field for posts, with a minus sign is reverse order
  # Options: date | title | or other field of front-matter
  post_order_by: "-date"

  # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，0 则不限制
  # The maximum number of posts in a single category. If the limit is exceeded, it will be displayed More. If 0 no limit
  post_limit: 10


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  enable: true
  banner_img:
  banner_img_height: 60
  banner_mask_alpha: 0.4
  subtitle:
  # 友链的成员项
  # Member item of page
  items:
    - title: "百品工作室"
      intro: "未来属于我们！"
      link: "https://baipin.pw"
      avatar: "https://baipin.pw/wp-content/uploads/2019/07/ABUIABACGAAg_bP2wwUorbiplQQwgAU4gAU.jpg"

    - title: "云游君的小站"
      intro: "希望能成为一个有趣的人。"
      link: "https://www.yunyoujun.cn"
      avatar: "https://cdn.jsdelivr.net/gh/YunYouJun/yunyoujun.github.io/images/avatar.jpg"

    - title: "Islauso の树洞"
      intro: "一只咸鱼肥宅，兼职学生党"
      link: "https://www.azusemisa.top"
      avatar: "https://cdn.jsdelivr.net/gh/xiao-lin52/cdn-assets/images/avatar.webp"

    - title: "優萌初華"
      intro: "琉璃的医学 & 编程笔记"
      link: "https://shoka.lostyu.me"
      avatar: "https://cdn.jsdelivr.net/gh/amehime/shoka@latest/images/avatar.jpg"

    - title: "东方幻梦"
      intro: "只是当时已惘然"
      link: "https://blog.badapple.pro/"
      avatar: "https://cdn.jsdelivr.net/gh/OrientalFantasy/file/logo/logo-160.jpg"

    - title: "笔记"
      intro: "记录生活中的精彩缤纷，为生活中的小惊喜而欢呼"
      link: "https://bynote.cn"
      avatar: "https://bynote.cn/images/blogbg/icon.png"

    - title: "爱即是诗的博客"
      intro: "一个关于GIS的博客"
      link: "https://aigisss.com/blog/"
      avatar: "https://aigisss.com/blog/images/profile/avatar.jpg"

    - title: "iceH的博客"
      intro: "咸鱼一条，啥也不是"
      link: "https://www.360rce.com"
      avatar: "https://api.btstu.cn/sjtx/api.php?lx=c1&format=images"

    - title: "Bryce's Club"
      intro: "啥都想学的程序员"
      link: "https://riris.cn"
      avatar: "https://riris.cn/img/blog/kenan.jpeg"

    - title: "Jasonの小窝"
      intro: "因为热爱，所以执着"
      link: "https://freeaas.com/"
      avatar: "https://www.freeaas.com/a/avatar.jpg"

    - title: "guole's Blog"
      intro: "保持理智，相信明天。"
      link: "https://guole.fun/"
      avatar: "https://guole.fun/img/gl.jpg"

    - title: "GZTime"
      intro: "Walking on the Time Axis."
      link: "https://blog.gztime.cc/"
      avatar: "https://cdn.gztime.cc/avatar/GZTime_2021.png"

    - title: "极星网–博客论坛"
      intro: "分享生活，交流技术。"
      link: "https://www.jixing.one/"
      avatar: "https://www.jixing.one/jixing.jpg"

    - title: "CairBin’s Blog"
      intro: "To be or not to be …"
      link: "https://cairbin.top"
      avatar: "https://cairbin.gitee.io/cair_img/img/bloglogo.png"

    - title: "米亚的鱼"
      intro: "Mia’s land.Tady má,vítr, mraky, ryby"
      link: "https://blog.miacraft.cn/"
      avatar: "https://blog.miacraft.cn/miafish.png"

    - title: "清山的博客"
      intro: "折腾鬼一个"
      link: "https://qingshaner.com"
      avatar: "https://qingshaner.oss-cn-hangzhou.aliyuncs.com/images/202205021359396.jpg"

    - title: 小罗的小窝
      intro: 爱好很广的萌新程序员
      link: https://xiao-luo17.github.io/
      avatar: https://xiao-luo17.github.io/img/avatar.jpg

    - title: 闪闪の小窝
      intro: 来玩！玩累了…就睡觉！没问题的！
      link: https://moechun.fun/
      avatar: https://img.moechun.fun/avatar/hanajiang-2.png

  # 当成员头像加载失败时，替换为指定图片
  # When the member avatar fails to load, replace the specified image
  onerror_avatar: /img/avatar.png




# 文章图片可点击放大
# Zoom feature of images
fancybox:
  enable: true
  # 放大后图片链接替换规则，可用于将压缩图片链接替换为原图片链接，如 ['-slim', ''] 是将链接中 `-slim` 移除；如果想使用正则请使用 `re:` 前缀，如 ['re:\\d{3,4}\\/\\d{3,4}\\/', '']
  # The image url replacement when zooming, the feature can be used to replace the compressed image to the original image, eg: ['-slim', ''] removes `-slim` from the image url when zooming; if you want to use regular, use prefix `re:`, eg: ['re:\\d{3,4}\\/\\d{3,4}\\/','']
  img_url_replace: ['', '']
  # 参考 https://fancyapps.com/docs/ui/quick-start
  #
  options:
    Hash: false # 关闭 hash
    Toolbar: # 自定义工具栏
      display:
        - counter
        - zoom
        - download
        - close
    Thumbs: # 使缩略图不再自动打开
      autoStart: false

# 数学公式，
# Mathematical formula.
math:
  enable: true

  #
  #
  options:
    tex:
    svg:

# 流程图，基于 mermaid-js，具体请见：https://hexo.fluid-dev.com/docs/guide/#mermaid-流程图
# Flow chart, based on mermaid-js, see: https://hexo.fluid-dev.com/docs/en/guide/#mermaid
mermaid:
  enable: true

  #
  # See: http://mermaid-js.github.io/mermaid/
  options:
    theme: forest

bgMusic:
  enable: true
  notice:
    normal: <strong>NOTICE</strong><br>本页有特别的背景音乐哟~ 点击导航栏上的音符图标，选一首播放吧~
    autoplay: <strong>NOTICE</strong><br>正在播放本页的背景音乐~ 点击导航栏上的音符图标看看吧~
  playing_icon: *music-playing-icon
  music_links:
    - https://music.163.com/#/my/m/music/playlist?id=7595783141











# 评论插件
# Comment plugin
comments:
  enable: true
  # 指定的插件，需要同时设置对应插件的必要参数
  # The specified plugin needs to set the necessary parameters at the same time
  # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis
  type: &comment-type twikoo

# Twikoo
# 基于腾讯云开发
# Based on Tencent CloudBase
# See: https://twikoo.js.org
twikoo:
  envId: https://twikoo-jin-yuhan.vercel.app/
  region: ap-shanghai
  path: window.location.pathname


#---------------------------
# 指定导出给 typescript 使用的网站配置项
#
#---------------------------
export_config:
  - pjax
  - loading_box:
    - enable
    - image_src
  - code:
    - copy_btn
    - fold
  # - fun_features
  # - lazyload
  # - web_analytics
  # - sidebar:
  #   - toc
  - index:
    - slogan
    - special_banner
  - fancybox
  - mermaid:
    - enable
    - options
  - bgMusic
  - comments
  - *comment-type
  # - search:
  #   - enable
  #   - path


static_prefix:
  # 内部静态
  # Internal static
  internal_js: /js
  internal_css: /css
  internal_img: /img

  anchor: https://cdn.jsdelivr.net/npm/anchor-js@4/

  github_markdown: https://cdn.jsdelivr.net/npm/github-markdown-css@4/

  jquery: https://cdn.jsdelivr.net/npm/jquery@3/dist/

  pjax: https://cdn.jsdelivr.net/npm/pjax@latest/

  bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@4/dist/

  highlightjs: https://cdn.jsdelivr.net/npm/highlight.js@10/

  prismjs: https://cdn.jsdelivr.net/npm/prismjs@1/

  typed: https://cdn.jsdelivr.net/npm/typed.js@2/lib/

  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/

  nprogress: https://cdn.jsdelivr.net/npm/nprogress@0/

  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/

  katex: https://cdn.jsdelivr.net/npm/katex@0/dist/

  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/

  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/

  mermaid: https://cdn.jsdelivr.net/npm/mermaid@8/dist/

  valine: https://cdn.jsdelivr.net/npm/valine@1/dist/

  waline: https://cdn.jsdelivr.net/npm/@waline/client@1/dist/

  gitalk: https://cdn.jsdelivr.net/npm/gitalk@1/dist/

  disqusjs: https://cdn.jsdelivr.net/npm/disqusjs@1/dist/

  twikoo: https://cdn.jsdelivr.net/npm/twikoo@1/dist/

  spine: https://unpkg.com/@esotericsoftware/spine-threejs@4.0.*/dist/iife/

  threejs: https://unpkg.com/three@0.141.0/build/

  hint: /lib/hint/
